#include "Main.h"

#include "JEngine/J_Audio.cpp"
#include "JEngine/J_Render.cpp"
#include "JEngine/J_Collision.cpp"
#include "JEngine/J_Error.cpp"
#include "JEngine/J_Input.cpp"
#include "JEngine/J_Math.cpp"
#include "JEngine/J_Time.cpp"
#include "JEngine/J_System.cpp"
#include "JEngine/J_Window.cpp"

#include "Platform.cpp"
#include "Button.cpp"
#include "Container.cpp"
#include "Entity.cpp"
#include "EntityHandler.cpp"
#include "Game.cpp"
#include "GameOver.cpp"
#include "Highscore.cpp"
#include "Player.cpp"
#include "Menu.cpp"
